name: dart2js_o0_mapper_exception
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  fetch_client: ^1.1.2
  firebase_js_interop: ^0.0.9
  pub_api_client: ^3.1.0

dev_dependencies:
  rexios_lints: ^10.0.1
